# Course Description {-}

## Course overview {-}

Are you prepared to undertake your Capstone project? Are you ready for life after college? In this course, you will learn necessary decision-making skills, and continue to develop your thought processes, to confidently say “yes!” Through Hon 301, you will be able to plan, execute, and articulate what motivates your choices and their relevance for your academic, professional, and community life—at UIC and beyond. By considering the Honors Capstone requirements, research design and methodology, writing and project management strategies, best practices for engaging faculty and professionals, awards applications, public speaking, career planning, and community and civic engagement, you will understand the ways in which your academic development and UIC experiences can transfer across myriad areas. The ultimate goal is to equip you with the skills, knowledge, and confidence to position you for success.

This seminar is discussion-based; you are expected to have completed the readings and assignments **before** each class in order to contribute original thoughts. The topics areinterleaved to allow time for the development of your Capstone idea throughout the semester. Out-of-class assignments include crafting a professional piece of writing, analysis of research and literature, professional writing and revisions, constructing Capstone ideas, seeking appropriate resources, and preparing for professional practices in the field.

## Course objectives {-}

+ Students will be able to identify different forms of research and methods for their Honors Capstone project.
+ Students will be able to identify the value of a Capstone project, including creating an action plan for how to execute one.
+ Students will be able to locate and apply for academic, travel, and scholarship awards, and apply their value to long term goals.
+ Students will be able to describe the value of work experience after graduating and its relation to graduate or professional school and career goals.
+ Students will be able to connect different forms of civic engagement and leadership skills to a disposition for life-long learning.
+ Students will be able to delve deeper into their passions and goals, reflecting on self and preparing for life after college.

## Course learning outcomes {-}

+ Identify what motivates your choices and their relevance for academic, professional, and community life at UIC and beyond.
+ Become aware of multiple research paradigms and methods while considering what’s best for your Capstone project.
+ Learn about multiple scholarship options available to advance your work, including research grants, travel awards, and mentorship opportunities.
+ Reflect on the different values provided by diverse experiences to advance your graduate or professional school, career, and long-term goals.
+ Consider civic engagement and leadership from multiple perspectives, and how these relate to living a life that values life-long learning.
+ Form connections with peers, colleagues, and professionals in and outside of UIC to enhance your growth and development—personally and professionally.